Release 2.14
proofpoint/helm pull request #10
Opened 2019-10-11 21:46 UTC by Ewocker

2019-10-12 03:05 UTC, rajatjindal approved these changes

2019-10-12 03:41 UTC, johngmyers requested changes
Address probable merge problem in tiller.go

2019-10-12 03:41 UTC, johngmyers commented on cmd/tiller/tiller.go
> +		go func() {
There's net add of one `{`, but I don't see where it's closed. The original #8 also indented the `http.ListenAndServe` if block, but that change isn't here.

2019-10-15 20:18 UTC, Ewocker commented
Done in another PR

2019-10-15 20:18 UTC, closed without merging